theme: jekyll-theme-tactile

exclude: [vendor]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "report"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://afr-f1.github.io"
plugins:
  - jekyll-sitemap

